### ISSUE TITLE
Runs in file directory rather than project root

### ISSUE THREAD

**Issue by jrajav** [steelbrain/flow-ide#62] opened 2017-01-28 17:56 UTC
This plugin runs Flow in the directory containing the current file, rather than the root project directory Atom is open to, or the project root as defined by the first parent directory with a .flowconfig file. This creates a problem when you have a Flow config that depends on `<PROJECT_ROOT>` in order to resolve certain modules with `module.name_mapper`, causing errors that only occur in flow-ide but not when running flow from the project root directory.

**Comment by steelbrain** [comment] 2017-01-28 21:03
@jrajav It runs in the current directory instead of the root directory because not everybodyhas `.flowconfig` in their root directories. People working on big projects often have repos with multiple packages or modules and each has it's own flowconfig and running flow in the root directory would be meaningless for those use cases.

Furthermore you mentioned that in your configuration you use PROJECT_ROOT, This package should not break it in anyway since `CWD` and `PROJECT_ROOT` are two separate configs and `PROJECT_ROOT` should stay the same anywhere in the subdir of the project. If it doesn't, then it's a bug in flow and you should open a bug in it's repository so they can fix it.

Closing as not a bug but feel free to continue discussing

**Closed by steelbrain** 2017-01-28 21:03 UTC

**Comment by jrajav** [comment] 2017-01-29 02:39
@steelbrain Yeah after further investigation today and modifying your plugin I found it that it's actually likely to be this bug in Flow again: https://github.com/facebook/flow/issues/3189

When running Flow on Windows, it sometimes hits issues with case sensitivity, and I still haven't down exactly when it occurs. Node's `exec` probably triggers it too though.
